name: Continuous Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    name: Check Markdown links
    steps:
      - name: Clone eslint-teamcity
        uses: actions/checkout@master
      - name: Check hyperlinks
        uses: gaurav-nelson/github-action-markdown-link-check@v1

  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    name: Build (${{ matrix.node-version }})
    steps:
      - name: Clone eslint-teamcity
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test

  coverage:
    runs-on: ubuntu-latest
    name: Report Coverage
    steps:
      - name: Clone eslint-teamcity
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: make test-coverage
      - name: Report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          flag-name: node-${{ matrix.node-version }}
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}



